### ISSUE TITLE
[Bug]: Japanese characters are garbled.

### ISSUE THREAD

**Issue by MiguelHorta** [n-ice-community/openttd-android#4]
### Version of OpenTTD

13.0.rev113, 13.0.rev114, 13.1.rev116

### Expected result

Normal startup

### Actual result

![01](https://user-images.githubusercontent.com/20793664/231704960-ad42387a-cdcf-4c02-8a09-d8595ef6e99f.jpg)

### Steps to reproduce

Error on title screen after starting as normal.

(Cloned from here https://github.com/OpenTTD/OpenTTD/issues/10645)

**Comment by Vamp898** [comment]
Just tested it on my (stock) Aquos Sense 7 and it looks as expected

![Screenshot_20240408-113821](https://github.com/n-ice-community/openttd-android/assets/26246878/95f1ba54-c504-4de8-9a5d-510d180db0f2)

Are you sure the fonts are not missing on your smartphone? As said, mine is stock, never installed and fonts or similar and works out is the box

**Comment by MiguelHorta** [comment]
I forgot to close this one. 13.4.rev120 should have this fixed, via this [https://github.com/n-ice-community/openttd-android/commit/9d4e769ab21221060a9621041384612610585edc](commit)
